# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "ExportFishLog"
version = "1.8"

[vcpkg]
version = "2023.08.09"
packages = ["fmt", "zlib", "nlohmann-json", "srell", "minizip"]

[find-package]
fmt = {}
zlib = {}
unofficial-minizip = {}
nlohmann_json = {}

[fetch-content.tomlplusplus]
git = "https://github.com/marzer/tomlplusplus"
tag = "dbc4bcecf20b7c45fe9d39ca2aa4b28c35e4e83a"

[fetch-content.glaze]
git = "https://github.com/stephenberry/glaze"
tag = "e7d2da91e38182885d602d792d6b1e24f24185a9"

[fetch-content.magic_enum]
git = "https://github.com/Neargye/magic_enum"
tag = "3437129f30c926e740ae5943cef27cd0b836c4be"

[target.xivres]
cmake-before = """
find_path(SRELL_INCLUDE_DIRS "srell.hpp")
"""
type = "static"
sources = ["xivres/impl/**.cpp", "xivres/include/**.h"]
include-directories = ["${SRELL_INCLUDE_DIRS}"]
alias = "xivres::xivres"
compile-features = ["cxx_std_23"]
windows.compile-definitions = ["NOMINMAX"]
link-libraries = ["unofficial::minizip::minizip", "ZLIB::ZLIB", "nlohmann_json::nlohmann_json"]
msvc.private-compile-options = ["/permissive-", "/w14640", "/EHsc", "/MP", "/utf-8"]

[target.ExportFishLog]
type = "executable"
sources = ["src/**.cpp", "src/**.hpp", "src/**.h"]
include-directories = ["xivres/include/"]
compile-features = ["cxx_std_23"]
windows.compile-definitions = ["NOMINMAX"]
link-libraries = ["tomlplusplus::tomlplusplus", "fmt::fmt", "glaze::glaze", "magic_enum::magic_enum", "xivres::xivres"]
msvc.private-compile-options = ["/permissive-", "/w14640", "/EHsc", "/MP", "/utf-8"]