# 如果提示找不到地址的话就把对应的signature给改掉
# 至于怎么找的话,请用ghidra或者ida
# 或者看GatherBuddy跟github.com/aers/FFXivClientStructs
[signatures]
fishlog = "48 8D 0D ? ? ? ? 41 0F B6 0C 08 41 B0 ? 84 D1 0F 95 C1"
spear_fishlog = "48 8D 0D ?? ?? ?? ?? 41 0F B6 0C 08 84 D1 40 0F 95 C7"
object_table = "48 8D 0D ? ? ? ? E8 ? ? ? ? 44 0F B6 83 ? ? ? ? C6 83"